### ISSUE TITLE
Initialize a Go server

### ISSUE THREAD

**Issue by mskalandunas** [mskalandunas/Robin#21]
Create a basic hello world go server.  I'd maybe use [echo](https://echo.labstack.com/) to do this.

**Acceptance Criteria:**
- Create a server with Go that, when running and requested at a specific port, returns a status code 200 and JSON response
- Add documentation to the README

**Comment by JacobPernell** [comment]
I am unsure if I did this right, but the first bullet point I think is done for the AC. For the documentation, what should be included in that?
