### ISSUE TITLE
Create UI design

### ISSUE THREAD

**Issue by JacobPernell** [mskalandunas/Robin#41]

**Comment by JacobPernell** [comment]
Started working on this using a free UI design kit: https://www.figma.com/file/YSDqSXUM2c4eIYDyLyb5q7/Robin?node-id=9%3A70

**Comment by JacobPernell** [comment]
Here are my thoughts for the screens and some high level ideas for what could appear in them. This isn't how I'd normally approach designing something, but I'm just trying to slap together this design super quickly in order to have something visual we can start implementing ASAP.

===
Screens:
Home - Landing page (when logged out)

Login 

Sign up 

Home/Dashboard (at a glance general overview when logged in)
- 5 upcoming scheduled content
- 5 most recent content
- Chart to show content created (by last 7/30/90 days), color-coded by social media account
- Button to create new content

View all content (/content)
- Display all upcoming scheduled and previously-created content
- Option to search/filter by keyword, date range, social media account
- Button to create new content

View individual content (GET /content/{content_ID}
- Display the date posted/scheduled to be posted
- Description of content
- Social media account(s)
- Media attached to content

Edit individual content
- Edit all elements available in the above ‘view individual content’ screen

Create a new post (POST /content)
- A form to input description, select which social accounts to post to, attach media files, and a date picker to select when to post the content

Settings

- Edit email/password login information
- Change profile photo
- Manage auth for social media account connection
- Delete account

User profile photo in lower left of screen
- Menu to log out

**Comment by mskalandunas** [comment]
Home/Dashboard (at a glance general overview when logged in)

> Chart to show content created (by last 7/30/90 days), color-coded by social media account

Can you describe what this shows?

> View all content (/content)

We'll need to show "archived" content as well via filter.

> View individual content (GET /content/{content_ID}

How were you thinking of showing this?

> Edit individual content

I'm assuming this is only scheduled content since any content that's already been posted can't be edited.

> Change profile photo

I'd leave this off for now or maybe include fallbacks since the user having a profile picture isn't all that important.  We also won't be allowing them to change profile pictures associated with their socials.  Maybe user initials?

**Comment by JacobPernell** [comment]
> Home/Dashboard (at a glance general overview when logged in)
> 
> > Chart to show content created (by last 7/30/90 days), color-coded by social media account
> 
> Can you describe what this shows?
I was thinking this could be a circle chart with a dropdown to select the time frame. Different colors could be represented on the graph to show the distribution of the amount of posts made to each account (e.g. 1/2 of the circle could be blue to represent posts to Facebook, 1/4 red for Instagram, and 1/4 yellow for some other social media) with the total number of posts made during the selected time frame displayed in the middle of the circle.


> 
> > View all content (/content)
> 
> We'll need to show "archived" content as well via filter.
How do you envision archived content to work? Is that just going to be the already-posted content?


> 
> > View individual content (GET /content/{content_ID}
> 
> How were you thinking of showing this?
One of two ways: either taken to a separate page (with breadcrumbs in the upper left) or a modal (to get practice with coding how to display them). This page would simply list the information in most likely this order: time of post/scheduled time, social accounts, attached media, description. It would *not* try to mimic the final look of how it'd appear on a social site.

> 
> > Edit individual content
> 
> I'm assuming this is only scheduled content since any content that's already been posted can't be edited.
> 
Correct.

> > Change profile photo
> 
> I'd leave this off for now or maybe include fallbacks since the user having a profile picture isn't all that important. We also won't be allowing them to change profile pictures associated with their socials. Maybe user initials?
Sounds good, I'm good with just initials in a colored circle or something similar.

**Comment by mskalandunas** [comment]
@JacobPernell

Archived content would be deleted content.

For the chart we'll maybe need to come up with a new endpoint but I'm down with that.

**Comment by JacobPernell** [comment]
I think the v1 is done and ready for review @mskalandunas. There a few details of this flow (like confirmation on trying to delete your account, the flow for actually hooking up your social accounts, etc. that I haven't done yet, but I think for now this is plenty to get started with implementing and we can sort out those design details later.

https://www.figma.com/file/YSDqSXUM2c4eIYDyLyb5q7/Robin?node-id=9%3A70

**Comment by JacobPernell** [comment]
![Robin - Web - Content - Filter Menu - Selected Items](https://user-images.githubusercontent.com/15975756/178132963-d8abe810-cca6-4ae7-b506-9df224c1a5ad.png)
![Robin - Web - Content - Filter Menu](https://user-images.githubusercontent.com/15975756/178132966-a26d07ce-7638-43d8-8a29-91b302d0040a.png)
![Robin - Web - Content - Filters Applied - Search](https://user-images.githubusercontent.com/15975756/178132967-a66945e3-ee02-443d-99e0-8973b04745a6.png)
![Robin - Web - Content - Filters Applied](https://user-images.githubusercontent.com/15975756/178132968-9ca3f888-d6f1-4d6e-9c24-bd210f3a972a.png)
![Robin - Web - Content - Skeleton Loading](https://user-images.githubusercontent.com/15975756/178132969-4339200c-44a5-4bcd-a645-1e6f8a529869.png)
![Robin - Web - Content - Upcoming](https://user-images.githubusercontent.com/15975756/178132970-503ad94b-1e31-40a5-966f-1ed6c6350fc6.png)
![Robin - Web - Dashboard - Delete Icon Hover](https://user-images.githubusercontent.com/15975756/178132971-244fb7a6-6b2b-4c4d-80a1-e9c61a43c369.png)
![Robin - Web - Dashboard - Edit Icon Hover](https://user-images.githubusercontent.com/15975756/178132972-4f1751fc-a166-42d4-acc3-9058a15c4eb5.png)
![Robin - Web - Dashboard - Scrolled Down](https://user-images.githubusercontent.com/15975756/178132973-5a5f1dbe-8b1a-4b67-98dc-b4203cfb9ba1.png)
![Robin - Web - Dashboard - View Icon Hover](https://user-images.githubusercontent.com/15975756/178132974-71c588e0-e6ad-475d-9d6f-5b343df100db.png)
![Robin - Web - Dashboard](https://user-images.githubusercontent.com/15975756/178132975-7df6a623-3fad-4697-bf47-81c2b89d96ab.png)
![Robin - Web - Edit Post - Select Date](https://user-images.githubusercontent.com/15975756/178132976-ac7ac7cd-c16c-4489-8231-5c2251bae765.png)
![Robin - Web - Edit Post-1](https://user-images.githubusercontent.com/15975756/178132977-2d184e7b-8b53-49d1-9b7f-2a422e5e4faf.png)
![Robin - Web - Edit Post](https://user-images.githubusercontent.com/15975756/178132979-0a2ad0fc-fea3-451b-b308-c1a380db9173.png)
![Robin - Web - Landing - Log In Button Hover](https://user-images.githubusercontent.com/15975756/178132980-f9365f7f-1c49-4f7e-bc48-2315ceb05374.png)
![Robin - Web - Landing - Primary Button Hover](https://user-images.githubusercontent.com/15975756/178132981-1a5c19fe-8ed9-44aa-ae33-a66d29d0fff4.png)
![Robin - Web - Landing](https://user-images.githubusercontent.com/15975756/178132982-96db01cc-c68b-47af-b007-150f33314d4f.png)
![Robin - Web - Log In - Placeholder Input Text](https://user-images.githubusercontent.com/15975756/178132983-77bf2244-0992-432c-958c-31a3e0e1e9ac.png)
![Robin - Web - Log In Error](https://user-images.githubusercontent.com/15975756/178132984-b11f26cf-6f9b-4a74-8da6-ae6d591d7f5b.png)
![Robin - Web - Nav Menu](https://user-images.githubusercontent.com/15975756/178132985-8c0b1a45-90e1-4d0e-81ba-83916a35f2b8.png)
![Robin - Web - Settings](https://user-images.githubusercontent.com/15975756/178132986-57e3ec84-b28d-4195-880a-79c60c6f19a2.png)
![Robin - Web - Sign up](https://user-images.githubusercontent.com/15975756/178132987-e228d843-debe-4147-9cb1-3ee3c0d371e0.png)
![Robin - Web - Social Account Button Hover](https://user-images.githubusercontent.com/15975756/178132988-6473ddf4-b26a-4633-ad3d-dc058c7e200b.png)
![Robin - Web - View Post](https://user-images.githubusercontent.com/15975756/178132989-de0d77ee-1cea-4f24-a073-44893ea07042.png)
