### ISSUE TITLE
Conceptualize a Content View implementation

### ISSUE THREAD

**Issue by mskalandunas** [mskalandunas/Robin#42]
# Description
This ticket is meant to be more of a discussion.  The assignee will present their ideas for how they might go about implementing the Content View.  Once all parties have signed off, this ticket is complete.

View:

<img src="https://user-images.githubusercontent.com/15975756/178132970-503ad94b-1e31-40a5-966f-1ed6c6350fc6.png" />
<img src="https://user-images.githubusercontent.com/15975756/178132968-9ca3f888-d6f1-4d6e-9c24-bd210f3a972a.png" />
<img src="https://user-images.githubusercontent.com/15975756/178132963-d8abe810-cca6-4ae7-b506-9df224c1a5ad.png" />
<img src="https://user-images.githubusercontent.com/15975756/178132969-4339200c-44a5-4bcd-a645-1e6f8a529869.png" />

# Sign-off
- [x] @JacobPernell 
- [x] @mskalandunas

**Comment by JacobPernell** [comment]
So before diving into the specifics of this content view, I'm wondering if it would be helpful to create a sort of higher-level page skeleton/framework component that can house the different sections. What I'm seeing are a left-side nav, a title, and some center content on every page, so maybe the first step is to create a kind of page template that can load in content. i.e. this 'bare bones' page template component could be used on every view in our app. Not sure if that's a good approach or not though.

Components would be made for each individual UI piece (and live in /src/components/): buttons (with props to control things like primary vs. secondary styling), badges, filter tags, and the table styling.

The data in the table would be coming from the backend. When the user navigates to the content page, it will trigger a GET request to the backend API `/content` endpoint to fetch that data object of all the Content associated with the logged-in user. The shape of the data is TBD by the backend side, but I'm thinking we could take this data and put it into an array of objects (sorted by Content 'status') to then display into the table. While the information is loading though, we should display the 'skeleton loader' design to indicate to the user that we're loading information.

One consideration not currently reflected in the design is: if we want to be able to sort the table by any particular column, would the data need to be stored in a different way at all?

Any time a filter is added (upon pressing the 'Apply' button in the filter dropdown) or removed (by pressing an X on the filter badge), I originally thought it should be calling another GET request to the /contents endpoint, with the appropriate query parameters (which would also be reflected in the URL, e.g. `/content?term="dogs"?start=01-01-2022&end=01-31-2022`). But on further consideration, I'm wondering if we only need to call the GET request once (upon initial navigation to this page) and perhaps store a copy of the fetched data locally. So then, any time we apply a filter or update the search input, it's simply filtering through the local data and displaying that in the table. This approach could reduce the amount of API calls we're making, but I'm not sure what best practice is here in this case.

Pressing the Create New button in the upper right corner will open the drawer in edit mode with no content filled in. When the user fills in all the info and clicks save, it will call `POST /content/`, which the backend will then handle creating a new `{content_id}`.

Pressing the trashcan/archive button on any given Content row should bring up a confirm modal/tooltip (not currently reflected in the design). Confirming the archive should request `DELETE /content/{content_id}`.

Pressing the edit icon button on any given Content row should call `GET /content/{content_id}` and open the right side drawer in edit mode with that content's information filled. This is not reflected in the design, but I'm wondering if we can disable the 'Save' button if no changes have been made in edit mode. Clicking the save button in the drawer should then call `PATCH /content/{content_id}` to update that particular post. I'm thinking we can have a local object that tracks changes in edit mode then gets pushed to the backend and overwrites the data on the server side.

Similarly, pressing the eye/view button will also call `GET /content/{content_id}` and open the drawer. But in this case, it should not display the save button in the drawer nor give the ability to edit given that this will be an already-posted piece of content.

**Comment by mskalandunas** [comment]
@JacobPernell 

> So before diving into the specifics of this content view, I'm wondering if it would be helpful to create a sort of higher-level page skeleton/framework component that can house the different sections. What I'm seeing are a left-side nav, a title, and some center content on every page, so maybe the first step is to create a kind of page template that can load in content. i.e. this 'bare bones' page template component could be used on every view in our app. Not sure if that's a good approach or not though.

I don't think a template's a good way to go about this, as we don't want to force pages to adhere to it.  Over time, page content tends to change which usually means teams add more and more to the template until it has many properties that all service different views, and in the end should just all be separate views.  I think in our case we'll want A view with a nav and to have its body content be composed of children of a router.

> Components would be made for each individual UI piece (and live in /src/components/): buttons (with props to control things like primary vs. secondary styling), badges, filter tags, and the table styling.

We may want to separate our generic components from our domain-specific ones.  Buttons and navigation for example should never need to know any domain-specific information.

> Any time a filter is added (upon pressing the 'Apply' button in the filter dropdown) or removed (by pressing an X on the filter badge), I originally thought it should be calling another GET request to the /contents endpoint, with the appropriate query parameters (which would also be reflected in the URL, e.g. /content?term="dogs"?start=01-01-2022&end=01-31-2022). But on further consideration, I'm wondering if we only need to call the GET request once (upon initial navigation to this page) and perhaps store a copy of the fetched data locally. So then, any time we apply a filter or update the search input, it's simply filtering through the local data and displaying that in the table. This approach could reduce the amount of API calls we're making, but I'm not sure what best practice is here in this case.

I'd recommend making those GETs.  If we want to cache we can do it on the backend.  This prevents the UI from displaying stale data, or if the list is greater than what was initially requested, it'll actually get the real results rather than filtered results from the initial API call.

> Pressing the trashcan/archive button on any given Content row should bring up a confirm modal/tooltip (not currently reflected in the design). Confirming the archive should request DELETE /content/{content_id}.

I think archiving and deleting should be separate -- archiving removes the content from the social networks it was posted to, delete removes it and deletes it, and all accompanying data/media from our databse.

> Similarly, pressing the eye/view button will also call GET /content/{content_id} and open the drawer. But in this case, it should not display the save button in the drawer nor give the ability to edit given that this will be an already-posted piece of content.

------

When it comes to our APIs, I'm more interested in how you think we should separate our APIs from our React code and our API clients from the APIs themselves.

Also, how will you structure components in general?  We'll have multiple views and I'd like to see what your plans are for managing multiple views in such a way that they're not interdependent. 

How do you plan on managing state across different components?

**Comment by JacobPernell** [comment]
@mskalandunas
Ok cool, thanks for these thoughts. Overall it makes sense.

> 
> When it comes to our APIs, I'm more interested in how you think we should separate our APIs from our React code and our API clients from the APIs themselves.
> 
I'm not really sure on this one. Does it make sense to have one main handler function serve as a bridge between our APIs and React code that can take in parameters for what type of HTTP request and what endpoint we want to call? And then some kind of backend handler function that can translate the shape of data to best fit the external APIs?

> Also, how will you structure components in general? We'll have multiple views and I'd like to see what your plans are for managing multiple views in such a way that they're not interdependent.
> 
> How do you plan on managing state across different components?

So I've only really used hooks and a little bit of class-based state too. But from the little that I know at a high level, would Redux be a good approach to handle the state of things like the table display and the drawers in a more global state store? I don't have enough experience or insight to know when one kind of state management is better than another though so I'm largely guessing here.

**Comment by mskalandunas** [comment]
> I'm not really sure on this one. Does it make sense to have one main handler function serve as a bridge between our APIs and React code that can take in parameters for what type of HTTP request and what endpoint we want to call? And then some kind of backend handler function that can translate the shape of data to best fit the external APIs?

How do you feel this would look?  Can you give an example? 

> So I've only really used hooks and a little bit of class-based state too. But from the little that I know at a high level, would Redux be a good approach to handle the state of things like the table display and the drawers in a more global state store? I don't have enough experience or insight to know when one kind of state management is better than another though so I'm largely guessing here.

I think Redux is a good idea here because we'll have lots of more global state.  I think we can better understand what solution we'll need to use by figuring out how we'll need to share data.  If we have many components needing similar data, then Redux is great because it offers that data essentially globally via the connect function or useSelector.  

Redux also depends largely on user actions.  We can get an idea of what actions we'll need to use Redux for by thinking through a user flow -- what is the user actually doing?  Would it make sense to translate those actions into Redux actions?

You mentioned the drawer, and I think this touches on an important topic which is separation of concerns.  The drawer, conceptually, is the kind of thing that can be opened in many views.  We may want to move its "open" state out of React or Redux entirely.  A user click could dispatch a Redux action that eventually fires an event.  That event could speak to a global event manager that the drawer is listening to, firing the open event.  After that, the drawer can manage its own close.

**Comment by JacobPernell** [comment]
> > I'm not really sure on this one. Does it make sense to have one main handler function serve as a bridge between our APIs and React code that can take in parameters for what type of HTTP request and what endpoint we want to call? And then some kind of backend handler function that can translate the shape of data to best fit the external APIs?
> 
> How do you feel this would look? Can you give an example?
>
This is rough around the edges, but for the former maybe something along these lines:
```
const handleHttpRequest = async (reqType = '', endpoint = '', data = {}) => {
  switch (reqType) {
    case 'GET':
      await fetch(endpoint, {
        method: reqType,
      });
      break;
    case 'POST':
      await fetch(endpoint, {
        method: reqType,
        body: JSON.stringify(data),
      });
      break;
    // etc.
    default:
      break;
  }
};
```

I'd need to look into the external API docs a bit further to think of how a handler function could work there.


> 
> > So I've only really used hooks and a little bit of class-based state too. But from the little that I know at a high level, would Redux be a good approach to handle the state of things like the table display and the drawers in a more global state store? I don't have enough experience or insight to know when one kind of state management is better than another though so I'm largely guessing here.
> 
> I think Redux is a good idea here because we'll have lots of more global state. I think we can better understand what solution we'll need to use by figuring out how we'll need to share data. If we have many components needing similar data, then Redux is great because it offers that data essentially globally via the connect function or useSelector.
> 
> Redux also depends largely on user actions. We can get an idea of what actions we'll need to use Redux for by thinking through a user flow -- what is the user actually doing? Would it make sense to translate those actions into Redux actions?
> 
Not sure if this is a rhetorical question, but if not, I'm not entirely sure the answer to this one. I think I'd need to do more research into how Redux works in order to have a better understanding of what Redux actions are and how they're used.

> You mentioned the drawer, and I think this touches on an important topic which is separation of concerns. The drawer, conceptually, is the kind of thing that can be opened in many views. We may want to move its "open" state out of React or Redux entirely. A user click could dispatch a Redux action that eventually fires an event. That event could speak to a global event manager that the drawer is listening to, firing the open event. After that, the drawer can manage its own close.

Interesting, that sounds cool. Does this mean then that we'd also want each individual button to also follow a similar pattern?

**Comment by mskalandunas** [comment]
Yup that Q is mostly rhetorical for the moment.  It's answerable but would take some thinking (and you knowing redux).

When it comes to the button/common question, consider _why_ components need to _not_ be common.  Once you answer that question, you can see how many common components you can have.  Keep in mind this isn't just _reusable_ components, but common components -- components usable in any project.  Domain-agnostic components.

When it comes to that handler, what is the benefit of using it?

**Comment by JacobPernell** [comment]
Sounds good. I'll spend some time looking into Redux a little more soon.

For the buttons, does this have to do with different components needing to do different things on different pages/within other components? So it's largely contextual, and therefore the buttons themselves shouldn't be handling all the logic directly esp for something like state management, but instead like I think you're saying, extract the logic out elsewhere and have the component itself just listen to updates from somewhere else to determine how it's presented?

For the handler I guess I was just trying to create a reusable function that could let us do these calls in one place, vs. having to make separate functions for e.g. handlePostReq(), handleGetReq(), etc.

**Comment by mskalandunas** [comment]
> For the buttons, does this have to do with different components needing to do different things on different pages/within other components? So it's largely contextual, and therefore the buttons themselves shouldn't be handling all the logic directly esp for something like state management, but instead like I think you're saying, extract the logic out elsewhere and have the component itself just listen to updates from somewhere else to determine how it's presented?

I think when you have a little more React experience you'll see what I mean.  Basically a button, or any common component, shouldn't need to know anything about the app using it.  It should just be able to be supplied with what it needs to do something.

When it comes to the handler, I think you'll need to spend more time with fetch before coming up with a reusable solution.  Fetch's interface already provides what you're suggesting as an interface, since the user is still having to pass in 'POST' or whatever the method it.  I think the real benefit of wrapping fetch is forcing developers to use the Promise it returns in a way that benefits the enterprise.  We'll talk about this more soon.  

I'm going to take what you've written and make some suggestions so we can get to a point of signing off.

**Comment by mskalandunas** [comment]
# Content View Implementation Review
This is the _first_ UI being implemented, so it'll require some extra care given that it'll establish the groundwork for common components like buttons and anchors as well as the structure that most other implementations will follow.

## Common Components
Common UI components should exist in a common directory and be treated like library components -- completely domain agnostic.  Examples of common components:

- Buttons
  - Anchors
- Images
- Select elements
- ...and many more

These are basically React representations of HTML elements that may need extra treatment for reasons of standardization or accessibility.

### Branding
Brand colors, spacing, and other standard variables should be set as CSS variables.  Colors, spacing, etc, should all be variables unless they're truly unique (colors should never be unique unless they're something like social brand colors).

## Navigation
Navigation should exist as if it were a library component even though it'll realistically only be used once.  It should be domain-agnostic.

## Pages and Templates
We do need a container to wrap our views.  This container should probably only include our nav and any other components that do not change on navigation.  Its child should be a component with a router that manages internal views.

## APIs
Keep API information abstracted away from the components.  We can create a client factory to manage APIs.  A client factory is essentially an interface built around a particular endpoint, enabling available request methods to that endpoint.  Here's an example of this interface:

```js
contentClient.post(data, successHandler, failureHandler);
```

This simple API offers a standardized way to provide data as well as a simple-to-understand method for managing fetch-end states (request success/fails).

## Filters
Filtering should be done with GET requests.  Caching should be handled on the server.  The client should be dumb and not worry about this.

## Global State
Redux will handle global state and we'll make sure that actions are only created to represent _user actions_.  For example, `POLLING_USER_DATA` is not a valid user action -- it's a system action.  The lines may occasionally blur, but that should be rare.

## Directory Structure
We should follow the following directory structure:

```
├── src
    ├── api
    ├── store
    ├── utils
    ├── view
    ├── bootstrap.js
    └── index.js
```
There're a lot more layers to this but I think this is a good place to start

**Comment by JacobPernell** [comment]
This is amazing. Thanks for writing all this out. This provides a lot of clarity and gives me a better context to work within moving forward.

**Comment by JacobPernell** [comment]
Signed off!
